config/routes.rb
Rails.application.routes.draw do
  root to: 'backdoor#secrets'

  get  'dom', to: 'challenges#dom'
  get  'dom/ination', to: 'challenges#dom_done'
  get  'secrets', to: 'backdoor#secrets', as: :secrets
  get  'access_denied', to: 'application#access_denied', as: :access_denied
  get  'encryption', to: 'encryption#new', as: :new_encryption
  post 'encryption', to: 'encryption#create', as: :encryption
  post 'github/pull_request', to: 'github#pull_request', as: :pull_request

  resources :completions
end

app/models/completion.rb
class Completion < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def access_denied
    render status: :unauthorized
  end
end

app/controllers/backdoor_controller.rb
class BackdoorController < ApplicationController
  has_mobile_fu
  has_mobile_fu_for :secrets

  def secrets
    redirect_to access_denied_path unless is_mobile_device?
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def dom
  end

  def dom_done
  end
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def index
    @completions = Completion.order('created_at ASC').limit(100)
  end

  def new
    @completion = Completion.new
  end

  def create
    redirect_to access_denied_path and return unless params[:password] == ENV['xyzzy']

    unless session[:completed]
      Completion.create(completion_params)
      session[:completed] = true
    end

    redirect_to completions_path
  end

  def completion_params
    params.require(:completion).permit(:display_name)
  end
end

app/controllers/encryption_controller.rb
class EncryptionController < ApplicationController
  def create
    @encrypted_data = Encryption.encrypt(params[:email])
  end
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
  def pull_request
    if pr_is_open?(params)
      encrypted_email = params[:pull_request][:title].strip
      email = Encryption.decrypt(encrypted_email)
      Rails.logger.info "Sending email to #{email}"
      PullRequestMailer.pr_received(email).deliver if email.match(/.+@.+/)
    end

    render nothing: true
  end

  private
    def pr_is_open?(params)
      params[:pull_request][:state] == 'open'
    end
end

app/views/application/access_denied.html.erb
<img id="access-denied" style="width: 100%;" src="http://vfa-tech-challenge.s3.amazonaws.com/access_denied.gif" />

<script type="text/javascript" charset="utf-8">
  setInterval(function() {
    $('#access-denied').toggle()
  }, 800);
</script>

app/views/application/home.html.erb
<img id="access-denied" style="width: 100%;" src="http://vfa-tech-challenge.s3.amazonaws.com/access_denied.gif" />

<script type="text/javascript" charset="utf-8">
  setInterval(function() {
    $('#access-denied').toggle()
  }, 800);
</script>

app/views/backdoor/secrets.mobile.erb
<h1>THE SECRET PASSWORD IS</h1>

<div>
  <pre>
    <%= ENV['THE_SECRET_PASSWORD'] %>
  </pre>
</div>

<p>
  Look at the README to see what to do next!
</p>

app/views/challenges/dom.html.erb
<div id="dom-challenge">
  <h1><span>DOMMMM <span class="medium">DOM</span> <span class="big">DOM</span> DOM <span class="biggest">DOMMMMMMM</span></h2>
  <p>Inspect the DOM to begin!</p>
  <!-- DOM Challenge -->
  <!-- Put the following elements in the correct order. -->

  <div id="qux" class="metasyntactic"></div>
  <div id="bar" class="metasyntactic"></div>
  <div id="baz" class="metasyntactic"></div>
  <div id="foo" class="metasyntactic"></div>
</div>

app/views/challenges/dom_done.html.erb
<div>
  <p>
    Nice work!
  </p>

  <p>
    For your next challenge, you must bypass the security of this page:
    <%= link_to secrets_url, secrets_url %>
  </p>

  <p>
    Provided below is the source code of the web application:
    <%= link_to 'https://github.com/spencer1248/spawncamping-octo-computing-machine', 'https://github.com/spencer1248/spawncamping-octo-computing-machine', target: '_blank' %>
  </p>

  <p>
    Read the README.md file for more information!
  </p>

  <p>
    Good luck!
  </p>
</div>

app/views/completions/index.html.erb
<h1>Finish Line</h1>

completion.display_name('Zach Kaufman & Karyn Vilbig');

<% if @completions.any? %>
<ol>
  <% @completions.each do |completion| %>
    <li style="font-size: 24px;"><%= completion.display_name %></li>
  <% end %>
</ol>
<% else %>
  <h3>No finishers yet!</h3>
<% end %>

<script type="text/javascript" charset="utf-8">
  setTimeout(function() {
    window.location = window.location;
  }, 5000);
</script>

app/views/completions/new.html.erb
<% if session[:completed] %>
  <p>Congrats, you did it!</p>
<% else %>
  <%= form_for @completion do |f| %>
    <div>
      <%= f.label :display_name %>
      <%= f.text_field :display_name %>
    </div>
    <div>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>
    <%= f.submit 'Finish!' %>
  <% end %>
<% end %>

app/views/encryption/create.html.erb
<pre>
  <%= @encrypted_data %>
</pre>

app/views/encryption/new.html.erb
<h1>AES-128 Encryption</h2>
<p>
  <a href="http://en.wikipedia.org/wiki/Advanced_Encryption_Standard">wikipedia</a>
</p>
<%= form_tag '/encryption' do %>
  <%= text_field_tag :email, '', placeholder: 'email' %>
  <%= submit_tag 'Encrypt'  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Capture the Flag</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <title>VFA Tech Challenge</title>
        <meta name="description" content="">
        <meta name="HandheldFriendly" content="True">
        <meta name="MobileOptimized" content="320">
        <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">
        <meta http-equiv="cleartype" content="on">

        <meta name="msapplication-TileImage" content="img/touch/apple-touch-icon-144x144-precomposed.png">
        <meta name="msapplication-TileColor" content="#222222">

        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-title" content="">

        <style type="text/css" media="all">
          body {
            background-color: #428bca;
            color: yellow;
          }
        </style>
    </head>
    <body>
        <%= yield %>
    </body>
</html>

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <title>VFA Tech Challenge</title>
        <meta name="description" content="">
        <meta name="HandheldFriendly" content="True">
        <meta name="MobileOptimized" content="320">
        <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">
        <meta http-equiv="cleartype" content="on">

        <meta name="msapplication-TileImage" content="img/touch/apple-touch-icon-144x144-precomposed.png">
        <meta name="msapplication-TileColor" content="#222222">

        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-title" content="">
    </head>
    <body>
        <%= yield %>
    </body>
</html>